site_name: Li's blog
site_url: https://206031.com/
site_author: enotaa33@gmail.com
site_description: 个人博客

repo_name: Li's blog GitHub repo
repo_url: https://github.com/Lijinyu3/lijinyu3.github.io
edit_uri: edit/main/docs/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Notes:
    - 'Harvard CS50':
      - 'Syllabus': 'notes/Harvard_CS50/0xFF_Syllabus.md'
      - 'Lec 00: Scratch': 'notes/Harvard_CS50/0x00_Scratch.md'
      - 'Lec 01: C': 'notes/Harvard_CS50/0x01_C.md'
      - 'Lec 02: Arrays': 'notes/Harvard_CS50/0x02_Arrays.md'
      - 'Lec 03: Algorithms': 'notes/Harvard_CS50/0x03_Algorithms.md'
      - 'Lec 04: Memory': 'notes/Harvard_CS50/0x04_Memory.md'
      - 'Lec 05: Data Structures': 'notes/Harvard_CS50/0x05_Data_Structures.md'
      - 'Lec 06: Python': 'notes/Harvard_CS50/0x06_Python.md'
      - 'Lec 07: SQL': 'notes/Harvard_CS50/0x07_SQL.md'
      - 'Lec 08: HTML, CSS, JS': 'notes/Harvard_CS50/0x08_HTML, CSS, JavaScript.md'
    - 'MIT 6.NULL': 'notes/MIT_6.NULL/'
      #      - 'Lec0. Scratch': 'notes/Harvard_CS50/0x00_Scratch.md'
      # - 'test': 'notes/Harvard_CS50/test.md'
theme:
  features:
    - navigation.tabs
    - navigation.top
    - toc.follow
    - toc.intergrate
  name: material
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/lambda
    repo: fontawesome/brands/github
    # logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - git-revision-date-localized
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences

